name: Build Android

on:
  workflow_dispatch:
  push:
    tags:
      - "*.*.*"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.13.5
      uses: actions/setup-python@v3
      with:
        python-version: "3.13.5"
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install uv
        uv sync --link-mode=copy

    - name: Build android apk
      run: uv run flet build apk --android-signing-key-store-password ${{ secrets.KEYSTORE_PASS }}

    - name: Upload artifacts.
      uses: actions/upload-artifact@v4
      with: 
        name: android-build
        path: build/apk
        if-no-files-found: error
        compression-level: 9
